### PR TITLE
Add minimal API connection

### PR DESCRIPTION
**Pull request by Quentinchampenois**

### CODE REVIEW

**Comment by Dynnammo** [comment]
It works by me @Quentinchampenois. Next step is to fix the CI stuff and next we merge.

**Comment by Quentinchampenois** [comment]
Github Actions doesn't work at the moment because of the working directory used in Actions. We will probably refactor the project tree next

**Comment by Dynnammo** [comment]
> Github Actions doesn't work at the moment because of the working directory used in Actions. We will probably refactor the project tree next

We may ask to @armandfardeau if we could solve this without changing the repo config.
Else @virgile-dev would you be against reorganizing the repo to have a gem-like app ? (indicators folder moved inside the Ruby code) ?

**Comment by armandfardeau** [comment]
@Dynnammo Everything should be fine now

**Review by Dynnammo — APPROVED** [review]

**Pull request merged**
